# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgui_state.proto\x12\x04UEWS\"\x0e\n\x0cStateRequest\"\x8d\x01\n\tGUI_State\x12\x17\n\nauto_alarm\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x18\n\x0bnew_inhibit\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x1b\n\x0emanual_pressed\x18\x03 \x01(\x08H\x02\x88\x01\x01\x42\r\n\x0b_auto_alarmB\x0e\n\x0c_new_inhibitB\x11\n\x0f_manual_pressedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gui_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATEREQUEST._serialized_start=25
  _STATEREQUEST._serialized_end=39
  _GUI_STATE._serialized_start=42
  _GUI_STATE._serialized_end=183
# @@protoc_insertion_point(module_scope)
