# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui_connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gui_connection.proto\x12\x04UEWS\"-\n\x13\x45stablishConnection\x12\x16\n\x0estate_lis_port\x18\x01 \x01(\x05\"H\n\x16\x45stablishConnectionAck\x12\x16\n\x0estate_req_port\x18\x01 \x01(\x05\x12\x16\n\x0egui_state_port\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gui_connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ESTABLISHCONNECTION._serialized_start=30
  _ESTABLISHCONNECTION._serialized_end=75
  _ESTABLISHCONNECTIONACK._serialized_start=77
  _ESTABLISHCONNECTIONACK._serialized_end=149
# @@protoc_insertion_point(module_scope)
