# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rsdf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrsdf.proto\x12\x04UEWS\"d\n\x04RSDF\x12\x10\n\x08raw_rsdf\x18\x01 \x01(\t\x12\x1a\n\rtime_dilation\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x12\n\x05reset\x18\x03 \x01(\x08H\x01\x88\x01\x01\x42\x10\n\x0e_time_dilationB\x08\n\x06_resetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rsdf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RSDF._serialized_start=20
  _RSDF._serialized_end=120
# @@protoc_insertion_point(module_scope)
