# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\x04UEWS\"{\n\nTSPIRecord\x12\r\n\x05index\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\x12\x0e\n\x06proj_x\x18\x05 \x01(\x02\x12\x0e\n\x06proj_y\x18\x06 \x01(\x02\x12\r\n\x05speed\x18\x07 \x01(\x02\x12\x0e\n\x06\x63ourse\x18\x08 \x01(\x02\".\n\tTSPIStore\x12!\n\x07records\x18\x01 \x03(\x0b\x32\x10.UEWS.TSPIRecord\"\xf9\x02\n\x05State\x12\x0f\n\x07valid_x\x18\x01 \x01(\x08\x12\x0f\n\x07valid_y\x18\x02 \x01(\x08\x12\x0f\n\x07valid_z\x18\x03 \x01(\x08\x12\x13\n\x0bvalid_speed\x18\x04 \x01(\x08\x12\x1b\n\x13\x65nough_valid_tracks\x18\x05 \x01(\x08\x12\x0e\n\x06sub_in\x18\x06 \x01(\x08\x12\x15\n\rproj_pos_good\x18\x07 \x01(\x08\x12\x11\n\tsend_warn\x18\x08 \x01(\x08\x12\x14\n\x0c\x61larm_enable\x18\t \x01(\x08\x12\x10\n\x08\x61larm_on\x18\n \x01(\x08\x12\x18\n\x10\x64\x65pth_violations\x18\x0b \x01(\x05\x12\x14\n\x0ctotal_alerts\x18\x0c \x01(\x05\x12\x0e\n\x06no_sub\x18\r \x01(\x05\x12\x19\n\x11total_valid_track\x18\x0e \x01(\x05\x12\x12\n\x05reset\x18  \x01(\x08H\x00\x88\x01\x01\x12\x10\n\x08raw_rsdf\x18\x0f \x01(\t\x12\x1e\n\x05store\x18\x10 \x01(\x0b\x32\x0f.UEWS.TSPIStoreB\x08\n\x06_resetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TSPIRECORD._serialized_start=21
  _TSPIRECORD._serialized_end=144
  _TSPISTORE._serialized_start=146
  _TSPISTORE._serialized_end=192
  _STATE._serialized_start=195
  _STATE._serialized_end=572
# @@protoc_insertion_point(module_scope)
